version: "3.8"
services: 
  app:
    build: ./app/
    image: myml-api:latest
    container_name: myml-api
    restart: unless-stopped
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    networks:
      - myml-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/test')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  web:
    image: nginx:latest
    container_name: myml-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - myml-network

networks:
  myml-network:
    name: myml-network
    driver: bridge